### ISSUE TITLE
EXAM05 bug 

### ISSUE THREAD

**Issue by rzafari42** [c-bertran/codeshell#1]
**Describe the bug**
Just launch an empty grademe and got 33/100 

**Screenshots**

**Desktop (please complete the following information):** 
 - OS: [e.g. iOS]: macos 
 - 
**Additional context**
[
<img width="920" alt="Capture d’écran 2022-02-11 à 18 21 54" src="https://user-images.githubusercontent.com/56769614/153638721-92282c17-b516-476b-9138-3d8d7b319852.png">
](url)

**Comment by c-bertran** [comment]
The bug has been fixed in the latest version
