### ISSUE TITLE
Expected outcome of microshell's example differs from what happens in bash

### ISSUE THREAD

**Issue by rodsmade** [c-bertran/codeshell#11]
**Describe the bug**
In microshell's subject (`/srcs/exams/04/microshell/subjects/fr_FR`), the examples suggest that the second occurrence of echo should be interpreted as a command, hence there should be a second line of output.

```
$>./microshell /usr/bin/echo WOOT "; microshell ;" "; ;" ";" /usr/bin/echo "is hell of fun"
WOOT ; microshell ; ; ;
is hell of fun
```

**Expected behavior**
Semicolons shall be interpreted literally inside double quotes, as per [the documentation](https://www.gnu.org/software/bash/manual/html_node/Double-Quotes.html).

The expected subject text should be:
```
$>./microshell /usr/bin/echo WOOT "; microshell ;" "; ;" ";" /usr/bin/echo "is hell of fun"
WOOT ; microshell ; ; ; ; /usr/bin/echo is hell of fun
```
as is bash's (see screenshot).

**Screenshots**
![image](https://github.com/c-bertran/42-exam-shell/assets/49699403/8a51d426-25a7-4f22-8a82-84b1e25fde68)

**Additional context**
Some other examples give misleading guidance and hence should be revised.

**Comment by rodsmade** [comment]
When doing the exercise I realised this behaves just like pipex where in order to invoke and test the program one must escape bash's special chars. Duh! nevermind :)

**Comment by c-bertran** [comment]
That's the joys of coding, but at least taking the time to fix a possible bug is very nice ^^
