### ISSUE TITLE
In get_prime_sum exercise  subject says to make get_prime_sum.c in get_prime_sum folder, but examshell when grades is searching for get_prime_sub.c in get_prime_sub folder

### ISSUE THREAD

**Issue by oshcheholev** [c-bertran/codeshell#13]
**Describe the bug**
In get_prime_sum exercise  subject says to make get_prime_sum.c in get_prime_sum folder, but examshell when grades is searching for get_prime_sub.c in get_prime_sub folder

**Comment by c-bertran** [comment]
Thank for this issue, i patch it as soon as possible

**Comment by c-bertran** [comment]
Issue is patched, new version is release.
If error persist, don't hesitate to reopen this issue
