### ISSUE TITLE
ERR_UNHANDLED_REJECTION

### ISSUE THREAD

**Issue by herthja** [c-bertran/codeshell#3]
═══════════════ ⚠  Error ⚠  ══════════════
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "127".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
══════════════════════════════════════════

**Comment by c-bertran** [comment]
Hello and thank you for posting an issue.
Could I have more details about what happened to you?

For example, the error occurred when starting the application, when launching an exam, a correction, etc...

Also, did you get the application via a git clone from the repo or via a release?

What OS are you on?

This would help me greatly to find the origin of the problem and therefore to correct it.

Thanks in advance

**Comment by herthja** [comment]
Hello and thank you very much for sharing the project.
I get the error after executing exam, it asks me for a password to install libraries.
sorry for my English.
![image](https://user-images.githubusercontent.com/32789061/183097405-9ab6e31d-7e8b-4754-8a3b-9391aab11163.png)

**Comment by c-bertran** [comment]
I think I know where the error comes from, I'll get back to you quickly

**Comment by c-bertran** [comment]
After a few hours of work I added a lot of security to prevent the program from receiving an unknown error.
So in the new release that just came out, in case of a bad password the program will simply ask for it again.
If the prompts are cancelled with ctrl+c, the default value is set, or the program stops correctly.

Tell me if with this new version you still have the crash, and if so put the new error message here which should be much more accurate.

Thanks in advance

**Comment by herthja** [comment]
Thank you for your work, I need install clang, git and valgrind.
![image](https://user-images.githubusercontent.com/32789061/183280559-469fe0c8-4160-4d92-be57-f88f7f173238.png)

**Comment by c-bertran** [comment]
The installation of these three external programs is normal, they are necessary for the functioning of the program

**Comment by c-bertran** [comment]
If your problem has been solved, please tell me so that I can close the issue

**Comment by jheszkn** [comment]
yes yes, my problem is solved, thank you very much for everything.
