### ISSUE TITLE
[Error 121]  Under MacOS, automatic installation is unavailable.

### ISSUE THREAD

**Issue by jdagz28** [c-bertran/codeshell#4]
[Error 121] Under MacOS, automatic installation is unavailable. Please install `git`, `clang` and `valgrind` manually

I have a High Sierra operating system. I have already installed git, clang and valgrind manually by homebrew but still can not make the installer work.

**Comment by c-bertran** [comment]
sorry for the delay, I'll look at it now

**Comment by c-bertran** [comment]
The project being completely redone from scratch I had not also taken the time to update the exams

**Comment by jdagz28** [comment]
Thank you for taking the time. I have installed:
git version 2.38.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
valgrind-3.16.1

**Comment by c-bertran** [comment]
The bug has been fixed in the brand new version from scratch, it is possible to skip the step in case of false negative
