### ISSUE TITLE
Exam Checkmate (02-part4)

### ISSUE THREAD

**Issue by Filoji** [c-bertran/codeshell#6]
**Describe the bug**
The subject of the Exam `checkmate` (02-part4) seems incorrect.

**Expected behavior**
The output of the third test should be `Fail$` since the king is not in checkmate in this position. Indeed, he is not aligned with the only rook on the board.

**Additional context**
[These lines seem problematic.](https://github.com/c-bertran/42-exam-shell/blob/68f0fc2702b508190d4948e00d4414124defc9fa/srcs/exams/02/part_4/checkmate/subjects/en_US#L21-L22)

**Comment by c-bertran** [comment]
I'll check if it's a mistake, I'll come back to you as soon as possible

**Comment by c-bertran** [comment]
After several tests there is indeed a problem with this exercise, the fix is in progress

**Comment by c-bertran** [comment]
The corrections to this exercise have been implemented
