### ISSUE TITLE
Fedora & MacOs grademe Error

### ISSUE THREAD

**Issue by pulgamecanica** [c-bertran/codeshell#7]
After installing the project in my computer and running the command grademe, inside the examshell cli the program returned an Error
```Error: Command failed: bash make.bash render```

Download the program at [Releases 0.3.6](https://github.com/c-bertran/42-exam-shell/releases/tag/0.3.6)
Change directory too the downloaded file location.
```chmod +x examshell && ./examshell```
When the command is executed, the Menu prompts there is a new version available for download
It says:
```? Do you want to skip installation step (e.g. a false negative) ? › (y/N)```
I decided to choose y (yes)
Then I choose English
Then Infinite
... Exam06
I create and commit the repo on the folder ~render/mini_serv/mini_serv.c
then I prompt grademe and the error is returned.

![image](https://user-images.githubusercontent.com/28810331/220395723-80fbd229-669b-464a-981d-43ecc0407438.png)

**Desktop (please complete the following information):**
 - OS: Fedora GNU/LINUX
 - Version 37

**Comment by pulgamecanica** [comment]
## I decided to test it on my macOS system and it failed as well...
***

<img width="754" alt="image" src="https://user-images.githubusercontent.com/28810331/220401207-d7908f6a-06ed-4706-80ab-4141d1fde48b.png">

***

Should I open a separate issue for the different OS?

**Comment by c-bertran** [comment]
Thank you for the report.
Naively and just to get over it, are clang, valgrind and git well installed?
Do the following commands output the versions ?

```
valgrind --version
clang --version
git --version
```

**Comment by c-bertran** [comment]
Apparently examshell does not detect two of these programs, which it absolutely needs to have in order to work properly

**Comment by pulgamecanica** [comment]
Hello, I don't have clang installed on my linux system, is it needed for this?
Nevertheless I share with you the following:
![image](https://user-images.githubusercontent.com/28810331/220411045-e4feac94-bf10-4f37-9d6d-f2ffd10c64fc.png)

**Comment by pulgamecanica** [comment]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/28810331/220411256-a1023329-d168-46d6-9faa-2b288646b793.png">
And this is from my macOS system, I don´t have valgrind in my macOS, since it's known to not work propery for my version 

- 3.4 GHz Quad-Core Intel Core i5
- MacOS Ventura 13.0.1 (22A400)

Again, is valgrind needed for macOS compilation? I can install it with brew if needed.

**Comment by c-bertran** [comment]
Actually examshell need git, clang and valgrind for working correctly.
Clang is used to compile programs and valgrind is needed to check for open leaks and fds.
The moulinette is included directly in examshell and does not require any external lib

**Comment by c-bertran** [comment]
The library verification system under Linux allows to automatically install the necessary packages
On the other hand under MacOS you have to do it manually, due to some limitations

**Comment by pulgamecanica** [comment]
I will install clang on Linux and will let you know.

**Comment by c-bertran** [comment]
Thank you for taking time to improve this software, it is very kind :)

**Comment by pulgamecanica** [comment]
Installed clang, on Linux, but the Error persists

![image](https://user-images.githubusercontent.com/28810331/220414679-55ce5dde-3d2d-4191-95b3-10dec8756664.png)
![image](https://user-images.githubusercontent.com/28810331/220414828-31f2510e-260d-42e8-adcd-e62a940f6bcc.png)

**Comment by c-bertran** [comment]
I'm on it in a hurry. Small question it's only with the exam 06that it happens or with any of them?
If it's the case I'll install Fedora and do unit tests on it

**Comment by pulgamecanica** [comment]
I will let you know in a few mins, I'll test some other test

**Comment by pulgamecanica** [comment]
Ok lol took me some time to pass Exam05, but it did work

***

![image](https://user-images.githubusercontent.com/28810331/220417427-9e470818-4ef1-49bc-b85f-19087acfb0f5.png)

**Comment by c-bertran** [comment]
Ok so this is a problem with the exam 06. I'll check it again, the bash being quite complex it's likely that there is an error

**Comment by pulgamecanica** [comment]
Gladd to be of help, also I will see if I can controibute any day hehe this project is actually amazing!

**Comment by c-bertran** [comment]
So basically the problem was very simple, on the exam 06, I use &>> to redirect all std to a file. But this format appeared on the versions of bash higher than 4. And many shells are still on version 3. So I switched to the old format > file 2>&1.
After checking my Mac understands the shell well. I have to fix a bug on the correction system and I could release the new version
