### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by pulgamecanica** [c-bertran/codeshell#9]
I believe it's a good idea to add to the README a **__Dependencies__** section

The Dependencies section will let any reader know which are the main dependencies that the project uses.
This way the reader will know if he needs to install any dependencies beforehand.
Although this could be arguable since Linux would detect this automatically and prompt the user to install them.

On the other hand I believe this information is useful and it's a good idea to have it on the README
and maybe explain why they are needed.
- node > version
- valgrind > version
- clang > version
- git > version

What do you think?

**Comment by c-bertran** [comment]
This is a great idea, it will be added as soon as possible

**Comment by c-bertran** [comment]
The indications on the dependencies have been added to the readme
